# Generated by Django 4.0.1 on 2022-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name of Strategy')),
                ('long_strategy', models.BooleanField(blank=True)),
                ('total_amount_of_coin', models.FloatField(blank=True, verbose_name='Total amount of coin')),
                ('number_of_orders', models.IntegerField(blank=True, verbose_name='Number of orders needed to make')),
                ('start_price', models.FloatField(blank=True, verbose_name='Current price of the coin')),
                ('first_margin', models.FloatField(blank=True, verbose_name='Margin of the first order')),
                ('max_set_margin', models.FloatField(blank=True, verbose_name='Total percentage of order set')),
                ('use_bnb', models.BooleanField(blank=True)),
            ],
        ),
    ]
