# Generated by Django 4.0.1 on 2022-02-08 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name of Strategy')),
                ('long_strategy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('date_strategy', models.DateField(default=django.utils.timezone.now, verbose_name='Strategy Date')),
                ('total_amount_of_coin', models.FloatField(blank=True, verbose_name='Total amount of coin')),
                ('number_of_orders', models.IntegerField(blank=True, verbose_name='Number of orders needed to make')),
                # ('margin', models.FloatField(blank=True, default=None, null=True, verbose_name='Orders margin')),
                ('start_price', models.FloatField(blank=True, verbose_name='Current price of the coin')),
                ('first_margin', models.FloatField(blank=True, verbose_name='Margin of the first order')),
                ('max_set_margin', models.FloatField(blank=True, verbose_name='Total percentage of order set')),
                ('use_bnb', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
    ]
