# Generated by Django 4.0.1 on 2022-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_strategy_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='profit',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Profit percentage'),
        ),
    ]
