# Generated by Django 4.0.1 on 2022-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_strategy_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='margin',
            field=models.FloatField(blank=True, default=0, verbose_name='Orders margin'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='profit',
            field=models.FloatField(blank=True, default=0, verbose_name='Profit percentage'),
        ),
    ]
