# Generated by Django 4.0.1 on 2022-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_alter_strategy_margin_alter_strategy_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='pair',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pair'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='start_price',
            field=models.FloatField(blank=True, verbose_name='Start price of the coin'),
        ),
    ]
